# Menu du site
[menus]
  [[menus.header]]
    name = 'Blog'
    url = '/blog'
    weight = 10
  [[menus.header]]
    name = 'Projets'
    url = '/projets'
    weight = 20
  [[menus.header]]
    name = 'Sandbox'
    url = '/sandbox'
    weight = 30
  [[menus.header]]
    name = 'Info'
    url = '/info'
    weight = 40

# Tags blog
[taxonomies]
  tag = 'tags'

# Langue par defaut du site
defaultContentLanguage = 'fr'

# Désactive les générations de termes dans le site
disableKinds = ['taxonomy', 'term']

# je sais plus
[markup.goldmark.renderHooks.image]
enableDefault = true
[markup.goldmark.renderHooks.link]
enableDefault = true

# Active l'HTML dans les fichiers markdown
[markup.goldmark.renderer]
  unsafe = true 