# Menu du site
[menus]
  [[menus.header]]
    name = 'Blog'
    url = '/blog'
    weight = 10
  [[menus.header]]
    name = 'Infos'
    url = '/infos'
    weight = 20

# Définition des taxonomies
[taxonomies]
  tag = "tags"

# Active les render hooks
[markup.goldmark.renderHooks.image]
enableDefault = true
[markup.goldmark.renderHooks.link]
enableDefault = true

# Active l'HTML dans les fichiers markdown
[markup.goldmark.renderer]
  unsafe = true 

# Empeche les images dans le markdown d'être englobé dans une balise paragraphe
[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false

# Format de la date 
[params]
  dateFormat = "January 2006"

# Accès aux infos de Git
enableGitInfo = true

# Generation de robot.txt
enableRobotsTXT = true