[menus]
  [[menus.header]]
    name = 'Blog'
    url = '/blog'
    weight = 10
  [[menus.header]]
    name = 'Projets'
    url = '/projets'
    weight = 20
  [[menus.header]]
    name = 'Sandbox'
    url = '/sandbox'
    weight = 30
  [[menus.header]]
    name = 'Info'
    url = '/info'
    weight = 40

defaultContentLanguage = 'fr'

disableKinds = ['taxonomy', 'term']

[markup.goldmark.renderHooks.image]
enableDefault = true

[markup.goldmark.renderHooks.link]
enableDefault = true