[menus]
  [[menus.header]]
    name = 'Blog'
    url = '/blog'
    weight = 10
  [[menus.header]]
    name = 'Info'
    url = '/info'
    weight = 20



disableKinds = ['taxonomyTerm', 'taxonomy', 'term']

[markup.goldmark.renderHooks.image]
enableDefault = true
[markup.goldmark.renderHooks.link]
enableDefault = true

[markup.goldmark.renderer]
  unsafe = true 

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false

[params]
  dateFormat = "January 2006"

enableGitInfo = true